name: Tecton CICD - plan/apply

on:
  pull_request:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest
    environment:
      name: prod-plan
    env:
      TECTON_API_KEY: ${{ secrets.PROD_API_KEY }}
      API_SERVICE: ${{ vars.API_SERVICE }}
      WORKSPACE: ${{ vars.PROD_WORKSPACE }}
    steps:
      - uses: actions/checkout@v3

      - name: print prod plan variables
        run: |
           echo Running plan on main push
           echo "dev API_SERVICE variable => $API_SERVICE"
           echo "dev WORKSPACE variable =>  $WORKSPACE"
           echo "dev TECTON_API_KEY variable =>  $TECTON_API_KEY"

    #   - name: Install Tecton CLI
    #     run: pip install -r requirements.txt

    #   - name: Select Development Tecton workspace
    #     run: tecton workspace select $WORKSPACE

    #   - name: Run Tecton plan
    #     run: 
    #         echo "Running Tecton plan in dev branch"
        
  apply:
    needs: [plan]
    runs-on: ubuntu-latest
    environment: 
        name: prod-deploy
    env:
        TECTON_API_KEY: ${{ secrets.PROD_API_KEY }}
        API_SERVICE: ${{ vars.API_SERVICE }}
        WORKSPACE: ${{ vars.PROD_WORKSPACE }}
    steps:
        - uses: actions/checkout@v3

        - name: print prod apply variables
          run: |
            echo Running apply on main push
            echo "dev API_SERVICE variable => $API_SERVICE"
            echo "dev WORKSPACE variable =>  $WORKSPACE"
            echo "dev TECTON_API_KEY variable =>  $TECTON_API_KEY"

        # - name: Install Tecton CLI
        #   run: pip install -r requirements.txt

        # - name: Select workspace
        #   run: tecton workspace select $WORKSPACE
        # - name: Run Tecton plan
        #   run: 
        #       echo "Running Tecton apply in dev branch"